<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Profile</name>
   <tag></tag>
   <elementGuidId>ca83f19c-6391-4f03-8985-1e8a17fc793e</elementGuidId>
   <imagePath>Screenshots/Targets/ProfileICON.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navbar-profile img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>Images/avator64.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Images/avator64.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/header[@class=&quot;topcontent ng-scope&quot;]/ov-header-wrap[@class=&quot;ng-scope ng-isolate-scope&quot;]/ov-header[@class=&quot;fixedmenu ng-isolate-scope&quot;]/div[@class=&quot;fixedmenu&quot;]/nav[@class=&quot;navbar navbar-inverse&quot;]/div[@class=&quot;container topBar&quot;]/div[@class=&quot;navbar-profile&quot;]/ul[@class=&quot;navprofile&quot;]/li[1]/span[@class=&quot;profile&quot;]/img[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screenshot</name>
      <type>Main</type>
      <value>C:/Users/Alex/Katalon Studio/Test/Screenshots/Targets/ProfileICON.png</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
   </webElementXpaths>
</WebElementEntity>
