<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveICON</name>
   <tag></tag>
   <elementGuidId>d23479f0-af8b-409c-bf3d-bcee95fcc0b0</elementGuidId>
   <imagePath>Screenshots/Targets/img_Create_header-icon.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='save new binder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>save new binder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.action(button.action)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>images/save32W.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/save32W.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/header[@class=&quot;topcontent ng-scope&quot;]/ov-header-wrap[@class=&quot;ng-scope ng-isolate-scope&quot;]/ov-header[@class=&quot;fixedmenu ng-isolate-scope&quot;]/div[@class=&quot;fixedmenu&quot;]/header[@class=&quot;jumbotron&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row row-header&quot;]/div[@class=&quot;gselection&quot;]/div[@class=&quot;icons ng-scope&quot;]/span[@class=&quot;ng-scope&quot;]/img[@class=&quot;header-icon&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screenshot</name>
      <type>Main</type>
      <value>C:/Users/Alex/Katalon Studio/Test/Screenshots/Targets/img_Create_header-icon.png</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='save new binder']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/img</value>
   </webElementXpaths>
</WebElementEntity>
