<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_TimeStamp</name>
   <tag></tag>
   <elementGuidId>3a611d90-949e-49f4-8a94-562ce930a97d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//th[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
