<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_Type</name>
   <tag></tag>
   <elementGuidId>1afaff4d-2e4b-4e70-bbec-a694e0b9f33c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//th[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
