<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_UserID</name>
   <tag></tag>
   <elementGuidId>88a287e5-8305-4af4-862d-c67bb2ffb72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//th[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
