<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_Template</name>
   <tag></tag>
   <elementGuidId>be525c38-303e-447a-9256-75f578e2a44e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//th[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
