<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_Value</name>
   <tag></tag>
   <elementGuidId>1c9278d5-4c41-4e3f-8128-8176520efa64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//th[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
