<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_TimeStampFilter</name>
   <tag></tag>
   <elementGuidId>083caa9d-6c53-4c17-b590-8b5b6985b816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[2]//a[1]//span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
