<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_TypeFilter</name>
   <tag></tag>
   <elementGuidId>b954097c-9eb1-4149-a28b-feff39cfa749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[5]//a[1]//span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
