<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_ValueFilter</name>
   <tag></tag>
   <elementGuidId>3e8ad851-df4f-4c67-9adf-d9c492d17d73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[7]//a[1]//span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
