<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_DescriptionKeyFilter</name>
   <tag></tag>
   <elementGuidId>2cb06ada-3780-4088-b390-58bf2a25849a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[4]//a[1]//span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
